// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/GithubLoader.ts";
import * as $$$2 from "./loaders/longRunning.ts";
import * as $$$1 from "./loaders/NewLoader.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/ItWorks.tsx";
import * as $$$$$$2 from "./sections/NewSection.tsx";
import * as $$$$$$3 from "./sections/Theme/Theme.tsx";
import * as $$$$$$4 from "./sections/Workflow.tsx";

const manifest = {
  "loaders": {
    "site/loaders/GithubLoader.ts": $$$0,
    "site/loaders/longRunning.ts": $$$2,
    "site/loaders/NewLoader.ts": $$$1,
  },
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/ItWorks.tsx": $$$$$$1,
    "site/sections/NewSection.tsx": $$$$$$2,
    "site/sections/Theme/Theme.tsx": $$$$$$3,
    "site/sections/Workflow.tsx": $$$$$$4,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
